[MemFunctions] Add c++11 flag.
We're using constexpr in the code, so this breaks in older systems.

MicroBenchmarks/MemFunctions/main.cpp:34:10: error: unknown type name 'constexpr'
  static constexpr size_t kMaxBufSizeBytes = 4096;

See https://reviews.llvm.org/D64082

git-svn-id: https://llvm.org/svn/llvm-project/test-suite/trunk@369888 91177308-0d34-0410-b5e6-96231b3b80d8